services:
  app_backend:
    build:
      context: ./backend 
      dockerfile: dockerfile

  app_frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_URL: "/api"