name: DevOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  TEST:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: app_data
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d app_data"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend/**
          sparse-checkout-cone-mode: false

      - name: Setting Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Running Pytests
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://admin:secret@localhost:5432/app_data
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pytest --maxfail=1 --junitxml=test_report.xml

      - name: Uploading Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Pytest Report
          path: ./backend/test_report.xml

  Pylint_Scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: [TEST]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend/**
          sparse-checkout-cone-mode: false

      - name: Running Pylint Scan
        run: >
          docker run
          --rm
          -v ${{github.workspace}}:/workspace
          cytopia/pylint
          /workspace/backend/app
          | tee pylint_report.txt
          || true

      - name: Uploading Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Pylint Report
          path: pylint_report.txt

  Flake8_Scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: [TEST]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend/**
          sparse-checkout-cone-mode: false

      - name: Running Pylint Scan
        run: >
          docker run
          --rm
          -v ${{github.workspace}}:/workspace
          alpine/flake8 /workspace/backend/app
          | tee flake8_report.txt
          || true

      - name: Uploading Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Flake8 Report
          path: flake8_report.txt
      
  Trivy_Scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        type: [backend, frontend]
    needs: [TEST]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Running Trivy Scan
        run: >
          docker run
          --rm
          -v ${{github.workspace}}:/workspace
          aquasec/trivy fs /workspace/${{matrix.type}}
          --severity HIGH,CRITICAL --no-progress --output /workspace/trivy_${{matrix.type}}_report.txt
          || true

      - name: Uploading Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Trivy ${{matrix.type}} Report
          path: trivy_${{matrix.type}}_report.txt
          
        
